require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const { notFound, errorHandler } = require('./src/middleware/errorMiddleware');
const app = express();
app.use(helmet());
app.use(cors());
app.use(express.json());
app.use(morgan('combined'));
app.use('/api/auth', require('./src/routes/authRoutes'));
app.use('/api/moods', require('./src/routes/moodRoutes'));
app.use('/api/profile', require('./src/routes/profileRoutes'));
app.use('/api/sessions', require('./src/routes/sessionRoutes'));
app.use('/api/resources', require('./src/routes/resourceRoutes'));
app.use('/api/forum', require('./src/routes/forumRoutes'));
app.use('/api/notifications', require('./src/routes/notificationRoutes'));
app.use('/api/admin', require('./src/routes/adminRoutes'));
app.use('/api/support', require('./src/routes/supportRoutes'));
app.use(notFound);
app.use(errorHandler);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => console.log(`Server running on port ${PORT}`));
